### ISSUE TITLE
[Bug] - actions not working

### ISSUE THREAD

**Issue by Elaniobro** [martiensk/vuex-jsdoc#3]
When I run the command to generate the docs, I do not see actions populating the docs.

```js
  /**
   * Submits the userSettings to database for persistent state.
   * @actions submitUserSettings=setCheckedRoles,setTimeFrame
   * @returns {void}
   */
```

```js
  /**
   * Fetches the userSettings based on the view to set the checkedRoles in state.
   * @actions fetchUserSettings=setCheckedRoles,setTimeFrame
   * @param {string} view NetworkId used to authenticate
   * @returns {void}
   */
```

**Comment by reisnobre** [comment]
Yeah, I'm having the same problem here.
State, Getters, and Mutators are ok, but actions won't work.

**Comment by Elaniobro** [comment]
👊 - bump

**Comment by LexLextter** [comment]
I am having the same problem - here is the error I am getting

`PATH\node_modules\jsdoc-vuex-plugin\lib\action.js:27
        e.doclet.memberof = e.doclet.memberof.replace('.actions', '');
                                              ^
TypeError: Cannot read property 'replace' of undefined
    at Object.exports.newDocletHandler (PATH\node_modules\jsdoc-vuex-plugin\lib\action.js:27:47)
    at Parser.newDoclet (PATH\node_modules\jsdoc-vuex-plugin\index.js:20:19)
    at Parser.emit (events.js:327:22)
    at addDoclet (PATH\node_modules\jsdoc\lib\jsdoc\src\handlers.js:157:16)
    at newSymbolDoclet (PATH\node_modules\jsdoc\lib\jsdoc\src\handlers.js:321:5)
    at Parser.<anonymous> (PATH\node_modules\jsdoc\lib\jsdoc\src\handlers.js:365:13)
    at Parser.emit (events.js:315:20)
    at Visitor.visitNode (PATH\node_modules\jsdoc\lib\jsdoc\src\visitor.js:846:20)
    at Visitor.visit (PATH\node_modules\jsdoc\lib\jsdoc\src\visitor.js:756:21)
    at Walker.recurse (PATH\node_modules\jsdoc\lib\jsdoc\src\walker.js:694:42)
    at Parser._walkAst (PATH\node_modules\jsdoc\lib\jsdoc\src\parser.js:305:22)
    at Parser._parseSourceCode (PATH\node_modules\jsdoc\lib\jsdoc\src\parser.js:296:22)
    at Parser.parse (PATH\node_modules\jsdoc\lib\jsdoc\src\parser.js:202:22)
    at Object.module.exports.cli.parseFiles (PATH\node_modules\jsdoc\cli.js:365:46)
    at module.exports.cli.main (PATH\node_modules\jsdoc\cli.js:234:18)
    at Object.module.exports.cli.runCommand (PATH\node_modules\jsdoc\cli.js:186:9)`

**Comment by martiensk** [comment]
Should be fixed now, thanks to @whoacowboy
